# Site settings
title:          Home
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            ""

# Author
author:
  name:         SeungAh Son
  url:          ""
  email:        gongsoonyee@gmail.com
  github:       seungahson

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
